g6jamm/stima

- pom.xml
- src/main/java/com/example/stima/domain/model/Role.java
- src/main/java/com/example/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/StimaApplication.java
- src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mock/UserRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/Role.java
- src/main/java/com/g6jamm/stima/domain/model/User.java
- src/main/java/com/g6jamm/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/stimaApplicationTests.java
> Renamed folder from example to g6jamm

- src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mock/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/Project.java
- src/main/java/com/g6jamm/stima/domain/model/SubProject.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
> Create Project class

- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mock/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
> Initialtask

- src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mock/SubProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/SubProject.java
- src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/resources/templates/subProject.html
> added subproject

- src/main/java/com/g6jamm/stima/data/repository/mock/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/resources/templates/Task.html
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Initial Create task

- src/main/java/com/g6jamm/stima/data/repository/mock/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/Project.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/main/resources/templates/project.html
- src/main/resources/templates/projects.html
> Project overview

- src/main/java/com/g6jamm/stima/data/repository/mock/TaskRepositoryStub.java
> Task stuff

- src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mock/UserRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/exception/SignUpException.java
- src/main/java/com/g6jamm/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
added new expception for SignUp Errors.
> Changed Exception Hanlding

- src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mock/SubProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/mock/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/SubProject.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/resources/templates/Task.html
- src/main/resources/templates/project.html
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Create subproject overview

- src/main/java/com/g6jamm/stima/data/repository/mock/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/mock/SubProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/mock/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/mock/UserRepositoryStub.java
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Staticmemory

- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Change mock to stub

- src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/exception/ResourceTypeNotFoundException.java
- src/main/java/com/g6jamm/stima/domain/exception/TaskCreationException.java
- src/main/java/com/g6jamm/stima/domain/model/ResourceType.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/resources/templates/Task.html
- src/main/resources/templates/project.html
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Resource type

- src/main/resources/static/data/install.sql
> Change order of drop tables

- src/main/java/com/g6jamm/stima/data/repository/util/DbManager.java
- src/main/java/com/g6jamm/stima/data/repository/util/DbSelector.java
- src/main/java/com/g6jamm/stima/data/repository/util/type/ConnectionType.java
> Add connection to DB

- src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/model/Project.java
- src/main/java/com/g6jamm/stima/domain/model/ProjectInterface.java
- src/main/java/com/g6jamm/stima/domain/model/SubProject.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
> Addtasktoproject

- install.sh
> remove unused variable from application.properties

- src/main/java/com/g6jamm/stima/web/UserController.java
> made logout work

- README.md
> Update link to prod

- src/main/resources/static/data/install.sql
> fixed naming in script

- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/main/resources/templates/fragments/projectFragment.html
- src/main/resources/templates/fragments/taskFragment.html
- src/main/resources/templates/project.html
- src/main/resources/templates/projects.html
> Templatebug

- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/resources/static/data/sample-data.sql
> fixed bug where lists where null

- src/main/java/com/g6jamm/stima/domain/model/Project.java
- src/main/java/com/g6jamm/stima/domain/model/SubProject.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/resources/templates/fragments/projectFragment.html
- src/main/resources/templates/fragments/taskFragment.html
en del af afleveringen (tror jeg?), vi kan tale om det i morgen
> Workday and ressource calc - still needs work

- .github/workflows/javaformat.yml
- .github/workflows/maven.yml
- .github/workflows/pull_request_target.yml
> Change ubuntu version

- src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
> Display projects per user

- src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectColorImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/resources/static/css/global.css
- src/main/resources/static/data/install.sql
- src/main/resources/static/data/sample-data.sql
- src/main/resources/templates/fragments/footerFragtment.html
- src/main/resources/templates/fragments/projectFragment.html
- src/main/resources/templates/project.html
- src/main/resources/templates/projects.html
> Add edit/delete option to projects

- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryStub.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/resources/static/data/sample-data.sql
- src/main/resources/templates/fragments/taskFragment.html
- src/main/resources/templates/project.html
- src/main/resources/templates/subProject.html
> Task edit2

- src/main/resources/static/css/global.css
- src/main/resources/templates/projects.html
> Fix plus card size

- src/main/java/com/g6jamm/stima/data/repository/ProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Exceptions

- src/main/java/com/g6jamm/stima/data/repository/ProjectColorRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectColorImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryMySQLImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
- src/main/java/com/g6jamm/stima/domain/service/ProjectService.java
- src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/resources/static/css/global.css
- src/main/resources/static/data/install.sql
- src/main/resources/static/data/sample-data.sql
> Fix colors using MySQL impl

- src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
- src/test/java/com/g6jamm/stima/test/TaskService/TaskServiceTest.java
> Fix dependency injections

- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/model/ProjectComposite.java
- src/main/java/com/g6jamm/stima/domain/model/ProjectLeaf.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/data/repository/stub/UserRepositoryStubTest.java
> Exceptions2

- src/main/java/com/g6jamm/stima/domain/model/ProjectComposite.java
- src/main/java/com/g6jamm/stima/domain/model/ProjectLeaf.java
- src/main/java/com/g6jamm/stima/domain/model/Task.java
- src/main/java/com/g6jamm/stima/domain/model/User.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/main/resources/static/data/sample-data.sql
- src/main/resources/templates/fragments/projectFragment.html
- src/main/resources/templates/fragments/taskFragment.html
- src/main/resources/templates/projects.html
> Fix create user

- src/main/resources/static/data/install.sql
- src/main/resources/static/data/sample-data.sql
> Fix db for Heroku

- src/main/resources/templates/createUser.html
- src/main/resources/templates/fragments/navFragment.html
- src/main/resources/templates/index.html
- src/main/resources/templates/project.html
- src/main/resources/templates/projects.html
- src/main/resources/templates/subProject.html
> Fix translation

- src/main/resources/templates/project.html
- src/main/resources/templates/projects.html
- src/main/resources/templates/subProject.html
Fix: https://github.com/g6jamm/stima/issues/113
> Fix empty btn cards

- src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
> Use user object instead of id in session

- src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
- src/main/resources/templates/fragments/navFragment.html
- src/test/java/com/g6jamm/stima/domain/service/UserServiceTest.java
> Create user from admin page

- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
> Improve MySql calls

- src/main/resources/static/data/install.sql
> Add cascade on delete

- src/main/resources/static/css/global.css
- src/main/resources/templates/fragments/headFragment.html
- src/main/resources/templates/fragments/projectFragment.html
- src/main/resources/templates/fragments/taskFragment.html
- src/main/resources/templates/index.html
> Google lighthouse

- src/main/java/com/g6jamm/stima/data/repository/mysql/UserRepositoryImpl.java
> Wrong resource name

- src/main/resources/templates/fragments/createUserFragment.html
- src/main/resources/templates/fragments/headFragment.html
- src/main/resources/templates/fragments/navFragment.html
- src/main/resources/templates/fragments/projectFragment.html
- src/main/resources/templates/fragments/taskFragment.html
- src/main/resources/templates/fragments/taskModalFragment.html
- src/main/resources/templates/index.html
- src/main/resources/templates/project.html
- src/main/resources/templates/projects.html
- src/main/resources/templates/subProject.html
> Fix all W3C validate warnings/erros

- src/main/resources/templates/projects.html
> fix validation

- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/service/TaskService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/resources/templates/fragments/taskFragment.html
> Fix delete task

- src/main/resources/templates/fragments/footerFragtment.html
- src/main/resources/templates/fragments/navFragment.html
> Add footer to container and fix logo text

- src/main/resources/templates/error.html
> Fix padding error page

- pom.xml
- src/main/java/com/g6jamm/stima/domain/service/ProjectColorService.java
- src/test/java/com/g6jamm/stima/data/repository/mysql/util/DbManagerTest.java
- src/test/java/com/g6jamm/stima/domain/service/TaskServiceTest.java
> Add IT test

- src/main/java/com/g6jamm/stima/data/repository/SubProjectRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectColorImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/util/DbManager.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/util/DbSelector.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectColorImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/SubProjectRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/exception/LoginException.java
- src/main/java/com/g6jamm/stima/domain/exception/SignUpException.java
- src/main/java/com/g6jamm/stima/domain/exception/SystemException.java
- src/main/java/com/g6jamm/stima/domain/exception/TaskCreationException.java
- src/main/java/com/g6jamm/stima/domain/model/Headproject.java
- src/main/java/com/g6jamm/stima/domain/model/Project.java
- src/main/java/com/g6jamm/stima/domain/model/Subproject.java
- src/main/java/com/g6jamm/stima/domain/service/SubProjectService.java
- src/main/java/com/g6jamm/stima/web/ProjectController.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
> Added javadoc og author, change misspelling in author

- src/main/java/com/g6jamm/stima/data/repository/PermissionRepository.java
- src/main/java/com/g6jamm/stima/data/repository/ResourceTypeRepository.java
- src/main/java/com/g6jamm/stima/data/repository/RoleRepository.java
- src/main/java/com/g6jamm/stima/data/repository/TaskRepository.java
- src/main/java/com/g6jamm/stima/data/repository/UserRepository.java
- src/main/java/com/g6jamm/stima/data/repository/mysql/ResourceTypeRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/PermissionRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/RoleRepositoryImpl.java
- src/main/java/com/g6jamm/stima/data/repository/stub/TaskRepositoryImpl.java
- src/main/java/com/g6jamm/stima/domain/model/Permission.java
- src/main/java/com/g6jamm/stima/domain/service/UserService.java
- src/main/java/com/g6jamm/stima/web/SubProjectController.java
- src/main/java/com/g6jamm/stima/web/UserController.java
> added author

- src/main/resources/templates/subProject.html
> fix delete task for subproject
